SEVERITY_ORDER = {"INFO": 0, "LOW": 1, "MEDIUM": 2, "HIGH": 3, "CRITICAL": 4}
RULE_EXPLAINERS = {
    "AUDIT_UNAVAILABLE": "The package-manager audit command could not run. Fix: verify the package manager is installed and rerun with network access if online audit is expected.",
    "DENY_PACKAGE": "Dependency is explicitly denied by policy denylist. Fix: remove or replace the package, or change policy only after explicit review.",
    "DENYLIST": "Dependency is explicitly denied by policy denylist. Fix: remove or replace the package, or change policy only after explicit review.",
    "DIRECT_URL": "Dependency is installed from a direct URL or VCS source. Fix: prefer a trusted registry package, pin to an immutable commit, and require explicit approval.",
    "FLOATING_VERSION": "Dependency version is not pinned exactly. Fix: pin exact versions to reduce supply-chain drift.",
    "INSTALL_SCRIPT": "npm install lifecycle script is present. Fix: review the script, disable scripts in CI when possible, or require explicit approval.",
    "INVALID_CSPROJ": "A .csproj file could not be parsed. Fix: repair the XML before relying on NuGet scan results.",
    "INVALID_DIRECTORY_PACKAGES_PROPS": "Directory.Packages.props could not be parsed. Fix: repair the XML before relying on central package scan results.",
    "INVALID_MANIFEST": "A package manifest could not be parsed. Fix: repair the manifest syntax and rerun the scan.",
    "INVALID_PACKAGE_LOCK": "package-lock.json could not be parsed. Fix: regenerate the lockfile with npm and commit the clean result.",
    "INVALID_PACKAGES_CONFIG": "packages.config could not be parsed. Fix: repair the XML or regenerate the file.",
    "INVALID_PACKAGES_LOCK": "packages.lock.json could not be parsed. Fix: regenerate the NuGet lockfile and commit the clean result.",
    "INVALID_PIPFILE_LOCK": "Pipfile.lock could not be parsed. Fix: regenerate the lockfile and rerun the scan.",
    "INVALID_PNPM_LOCK": "pnpm-lock.yaml could not be parsed. Fix: regenerate the lockfile with pnpm and commit the clean result.",
    "INVALID_PYPROJECT": "pyproject.toml could not be parsed. Fix: repair TOML syntax before relying on Python dependency scan results.",
    "INVALID_UV_LOCK": "uv.lock could not be parsed. Fix: regenerate the lockfile with uv and commit the clean result.",
    "KNOWN_VULNERABILITY": "Package/version matches a known vulnerability from configured intelligence sources. Fix: upgrade, patch, or baseline temporarily with explicit review.",
    "MAINTAINER_CHANGE_RISK": "Maintainer ownership changed beyond configured threshold. Fix: review repository ownership and release provenance before approval.",
    "MISSING_LOCKFILE": "Manifest exists but lockfile is missing while lockfiles are required. Fix: generate and commit the ecosystem lockfile.",
    "NPM_AUDIT": "npm audit reported high or critical vulnerabilities. Fix: run npm audit locally, upgrade/remediate, then rerun SafeDeps.",
    "PACKAGE_TOO_NEW": "Package is newer than configured minimum age threshold. Fix: delay adoption or require elevated review.",
    "PNPM_YAML_PARSER_MISSING": "pnpm-lock.yaml was found but YAML parsing is unavailable. Fix: install the dev dependencies including PyYAML.",
    "PUBLISHER_CHURN": "Publisher/owner changed too frequently in the configured time window. Fix: investigate ownership history before approval.",
    "SUSPICIOUS_NAME": "Package name matches suspicious supply-chain naming patterns. Fix: verify publisher, repository, age, and download history.",
    "TYPOSQUATTING_RISK": "Package name appears similar to protected/high-value packages and may be typosquatting. Fix: verify spelling, publisher identity, and source.",
    "UNPINNED_VERSION": "Dependency version is not pinned exactly. Fix: pin exact versions with the ecosystem's exact-version syntax.",
    "UNTRUSTED_INDEX": "Dependency source/registry is not in allowed registries. Fix: use a trusted registry or add a temporary policy exception after review.",
    "UNTRUSTED_REGISTRY": "Dependency source/registry is not in allowed registries. Fix: use a trusted registry or add a temporary policy exception after review.",
}
